// dmacp-app/src/components/Visualization.svelte
<script>
import * as d3 from 'd3';
import { onMount } from 'svelte';

    export let data;

    let width;
    let height;
    let xScale = () => {};
    let xTicks = [];
    let yScale = () => {};
    let scaledEntities = [];
    let scaledIntervals = [];

    const xValues = data.map(essay => essay.map(narration => narration.entityTimePosition.map( entity => entity.x ))).flat(2)
    const yValues = data.map(essay => essay.map(narration => narration.entityTimePosition.map( entity => entity.y ))).flat(2)
    const narrationValues = data.map((essay , e) => e)

    onMount(async () => {
        width = document.getElementById("container").clientWidth
        height = document.getElementById("container").clientHeight

        xScale = d3.scaleSymlog().domain(d3.extent(xValues.map(d => { return d }))).range([100, width -100])
        yScale = d3.scaleLinear().domain(d3.extent(yValues.map(d => { return d }))).range([30, height - 10])

        xTicks = xScale.ticks()

        scaledEntities = data.map((essay, e) => {
        return essay.map((narration) => {
            return narration.entityTimePosition.map( (entity) => {
                return {
                        narration: e,
                        textualLabel: entity.label,
                        cx: xScale(entity.x),
                        cy: yScale(entity.y),
                        type: narration.type
                    }
                } )
            })
        }).flat(2)
        

        scaledIntervals = data.map((essay, e) => {
        return essay.map((narration) => {
            return narration.entityTimePosition.map( (entity) => {
                return {
                        narration: e,
                        textualLabel: entity.label,
                        cx: xScale(entity.x),
                        cy: yScale(entity.y),
                        type: narration.type
                    }
                }).filter(entity => entity.type === 'interval')
            })
        }).flat(2)

        console.log(scaledIntervals)

    })

</script>
<div>
    <div id="container">
        <svg width="{ width }" height="{ height }">
            <g>
                {#each xTicks as tick}
                    <g transform="translate({ xScale(tick) }, 10)">
                        <text x="0" y="0">{ tick }</text>
                        <line x1="0" x2="0" y1="0" y2="{ height }" stroke="black"/>
                    </g>
                {:else}
                    <!-- <text>loading</text> -->
                {/each}
            </g>
            {#each scaledEntities as value}
                <circle cx="{ value.cx }" cy="{ value.cy }" r="5"/>
                <g transform="translate(10, 0)">
                    <text x="{ value.cx }" y="{ value.cy }">{ value.textualLabel }</text>
                </g>
            {:else}
                <text>loading</text>
            {/each}
        </svg>
    </div>
</div>
<style>

    #container {
        height: 92vh;
        /* width: 80vw; */
    }

    svg {
        /* width: 100%; */
        background-color: rgb(218, 254, 255);
    }

    svg circle {
        fill: red;
    }

    svg text {
        font-size: 10px;
    }

</style>

// dmacp-app/src/components/Visualization.vue
<template>
  <div class="visualization-container" ref="visualization">
    <svg :width="sizes.width" :height="sizes.height">
      <Filters :sizes="sizes"/>
      <g v-for="(tick, t) in xTicks" :key="`${t}-tick`" :transform="`translate(${xScale(tick)}, 0)`">
        <line x1="0" x2="0" y1="0" :y2="sizes.height" class="axis" />
      </g>
      <Intervals :data="data" :scales="{ xScale, yScale }" :ticks="xTicks"/>
      <Dots :data="data" :scales="{ xScale, yScale }" />
    </svg>
  </div>
</template>

<script>
import { mapState } from 'vuex'
import { scaleSymlog, scaleLinear } from 'd3-scale'
import { extent, mode } from 'd3-array'
import Dots from './visualization-components/Dots.vue'
import Intervals from './visualization-components/Intervals.vue'
import Filters from './visualization-components/SvgFilters.vue'


export default {
  name: 'Visualization',
  components: {
    Dots,
    Intervals,
    Filters
  },
  data () {
    return {
      sizes: { height: 0, width: 0 },
      xTicks: []
    }
  },
  computed: {
    ...mapState(['data']),
    xValues () { return this.data.map(essay => essay.map(narration => narration.entityTimePosition.map( entity => entity.x ))).flat(2) },
    yValues () { return this.data.map(essay => essay.map(narration => narration.entityTimePosition.map( entity => entity.y ))).flat(2) },
    xValuesMode () { return mode(this.xValues) }, 
    xScale () {
      const width = this.sizes.width
      const { xValues, xValuesMode } = this
      const xScale_ = scaleSymlog()
                        .domain(extent(xValues.map(d => { return d})))
                        .constant(1).range([100, 1.33*width])
                        .clamp(false)
                        .nice()

      this.storeRealScale(xScale_)

      return (x) => { return xScale_(x-xValuesMode) }
    },
    yScale () {
      const height = this.sizes.height
      const { yValues } = this
      return scaleLinear()
                .domain(extent(yValues.map(d => { return d })))
                .range([30, height - 30])
    }
  },
  mounted () {
    this.calcContainerSize()
 },
  methods: {
        calcContainerSize () {
          const { visualization } = this.$refs
          let cHeight = visualization.clientHeight
          let cWidth = visualization.clientWidth

          this.sizes.height = cHeight
          this.sizes.width = cWidth
    },
    storeRealScale (scale) {
      this.xTicks = scale.ticks(5)
    }
  }
}
</script>
