// dmacp-svelte-legacy/src/components/Visualization.svelte
<script>
import * as d3 from 'd3';
import { onMount } from 'svelte';
import Curves from './Curves.svelte';


    export let data;

    let width;
    let height;
    let xScale = () => {};
    let xTicks = [];
    let yScale = () => {};
    let scaledEntities = [];
    let scaledIntervals = [];

    // Come up with a temporal scale that maps to pixels and then remap for log? See: https://stackoverflow.com/questions/30672392/logarithmic-time-scale
    const xValues = data.map(essay => essay.map(narration => narration.entityTimePosition.map( entity => entity.x ))).flat(2)
    const yValues = data.map(essay => essay.map(narration => narration.entityTimePosition.map( entity => entity.y ))).flat(2)
    // const narrationValues = data.map((essay , e) => e)
    onMount(async () => {
        width = document.getElementById("container").clientWidth
        height = document.getElementById("container").clientHeight

        let xScale_ = d3.scaleSymlog().domain(d3.extent(xValues.map(d => { return d}))).constant(1).range([100, 1.33*width]).clamp(false).nice()
        yScale = d3.scaleLinear().domain(d3.extent(yValues.map(d => { return d }))).range([30, height - 30])
				
				// overwrite scale function and shift cener to 1945
				xScale = (x) => { return xScale_(x-1945) }
        xTicks = xScale_.ticks(5)

        scaledEntities = data.map((essay, e) => {
        return essay.map((narration) => {
            // console.log(narration)
            return narration.entityTimePosition.map( (entity) => {
                return {
                        narration: e,
                        id: narration.resource,
                        textualLabel: entity.label,
                        cx: xScale(entity.x),
                        cy: yScale(entity.y),
                        type: narration.type,
                        context: narration.intervalContext,
                        targets: narration.targets
                    }
                } )
            })
        }).flat(2)   
        
        scaledIntervals = data.map((essay, e) => {
        return essay.map((narration) => {
            let x1 = 0;
            let x2 = 0;
            const entityLength = narration.entityTimePosition.length
            if (entityLength > 0) {
                x1 = xScale(narration.entityTimePosition[0].x)
                x2 = entityLength < 2 ? xScale(d3.max(xTicks.map(d => { return d }))) : xScale(narration.entityTimePosition[entityLength - 1].x)
            }

            return narration.entityTimePosition.map( (entity) => {
                const definitionOfInterval = x2 === xScale(d3.max(xTicks.map(d => { return d }))) ? 'indefinite' : 'finite'
                const y = yScale(entity.y);
                return {
                        narration: e,
                        x1,
                        x2,
                        y1: y,
                        type: narration.type,
                        indefinite: definitionOfInterval,
                        context: narration.intervalContext
                    }
                }).filter(entity => entity.type === 'interval')
            })
        }).flat(2)

    })

</script>
<div>
    <div id="container">
        <svg width="{ width }" height="{ height }">
            <defs>
                <linearGradient id="begin-grad" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="0%" style="stop-color:#d8d8d8;stop-opacity:1"/>
                    <stop offset="50%" style="stop-color:rgb(255,255,255);stop-opacity:0" />
                </linearGradient>
                <linearGradient id="end-grad" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="100%" style="stop-color:#d8d8d8;stop-opacity:1"/>
                    <stop offset="50%" style="stop-color:rgb(255,255,255);stop-opacity:0" />
                </linearGradient>
            </defs>
            <g>
                <g transform="translate({ xScale(2021) }, 0)" class="now-tick">
                    <line x1="0" x2="0" y1="0" y2="{ height }" stroke="black"/>
                    <text x="5" y="15">Now</text>
                </g>
                {#each xTicks as tick}
                    <g transform="translate({ xScale(tick) }, 0)" class="tick">
                        <text x="880" y="-5" transform="rotate(90)" text-anchor="end">{ tick }</text>
                        <line x1="0" x2="0" y1="0" y2="{ height }" stroke="black"/>
                    </g>
                {:else}
                 <!-- svelte-ignore empty-block -->
                {/each}
            </g>
            {#each scaledIntervals as value}
                {#if value.indefinite === 'indefinite' }
                    <rect x="{ value.x1 }" width="{ value.x2 }" y="{ value.y1 - 1 }" height="2" class="{ value.context }"/>
                {:else}
                    <line x1="{ value.x1 }" x2="{ value.x2 }" y1="{ value.y1 }" y2="{ value.y1 }" class="{ value.indefinite }"/>
                {/if}
            {:else}
                <text>loading</text>
            {/each}
            {#if scaledEntities.length !== 0}
                <Curves scaledEntities='{scaledEntities}'/>
            {/if}
            {#each scaledEntities as value}
            <g class="entity">
                <circle cx="{ value.cx }" cy="{ value.cy }" r="2"/>
                <g transform="translate(10, 0)" class="label">
                    <text x="{ value.cx }" y="{ value.cy }">{ value.textualLabel }</text>
                </g>
            </g>
            {:else}
                <text>loading</text>
            {/each}
        </svg>
    </div>
</div>
<style>

    #container {
        height: 92vh;
        /* width: 80vw; */
    }

    svg {
        /* width: 100%; */
        border: 1px solid black;
    }

    g.tick > line {
        stroke-dasharray: 1 3;
    }

    .now-tick {
        fill: red;
    }

    .tick text {
        font-size: 8px;
    }

    svg circle {
        fill: white;
        stroke: black;
    }

    .label {
        opacity: 0;
    }

    .entity:hover > .label {
        opacity: 1;
    }

    .entity:hover circle {
        fill: rgb(29, 29, 29);
    }

    .is-end {
        fill: url(#end-grad);
        transform: translate(-100%, 0)
    }

    .is-beginning {
        fill: url(#begin-grad);
    }

    .finite {
        stroke: rgb(128, 128, 128);
        stroke-width: 2;
    }

    svg text {
        font-size: 10px;
    }

</style>

// dmacp-app/src/components/Visualization.vue
<template>
  <div class="visualization-container" ref="visualization">
    <svg :width="sizes.width" :height="sizes.height">
      <Filters :sizes="sizes"/>
      <g class="ticks">
        <g v-for="(tick, t) in xTicks" :key="`${t}-tickX`" :transform="`translate(${xScale(tick)}, 0)`">
          <line x1="0" x2="0" y1="0" :y2="sizes.height" class="axis" />
        </g>
        <g v-if="compress === false">
          <g v-for="(tick, t) in yTicks" :key="`${t}-tickY`" :transform="`translate(0, ${yScale(tick)})`">
            <line y1="0" y2="0" x1="0" :x2="sizes.width" class="axis" />
            <text x="10" y="-10">{{tick}}</text>
          </g>
        </g>
        <g v-else>
          <line :y1="sizes.height / 2" :y2="sizes.height / 2" x1="0" :x2="sizes.width" class="axis" />
        </g>
      </g>
      <Intervals v-if="compress === false" :data="data" :scales="{ xScale, yScale }" :ticks="xTicks"/>
      <Dots :scaled-entities="scaledEntities" :scales="{ xScale, yScale }" />
    </svg>
  </div>
</template>

<script>
import { mapState } from 'vuex'
import { scaleSymlog, scaleLinear } from 'd3-scale'
import { extent, mode } from 'd3-array'
import Dots from './visualization-components/Dots.vue'
import Intervals from './visualization-components/Intervals.vue'
import Filters from './visualization-components/SvgFilters.vue'


export default {
  name: 'Visualization',
  components: {
    Dots,
    Intervals,
    Filters
  },
  data () {
    return {
      sizes: { height: 0, width: 0 },
      xTicks: []
      //compress: false
    }
  },
  computed: {
    ...mapState(['data', 'compress']),
    xValues () { return this.data.map(essay => essay.map(narration => narration.entityTimePosition.map( entity => entity.x ))).flat(2) },
    yValues () { return this.data.map(essay => essay.map(narration => narration.entityTimePosition.map( entity => entity.y ))).flat(2) },
    xValuesMode () { return mode(this.xValues) }, 
    xScale () {
      const width = this.sizes.width
      const { xValues, xValuesMode } = this
      const xScale_ = scaleSymlog()
                        .domain(extent(xValues.map(d => { return d})))
                        .constant(1).range([100, 1.33*width])
                        .clamp(false)
                        .nice()

      this.storeRealScale(xScale_)

      return (x) => { return xScale_(x-xValuesMode) }
    },
    yScale () {
      const height = this.sizes.height
      const { yValues } = this
      return scaleLinear()
                .domain(extent(yValues.map(d => { return d })))
                .range([30, height - 30])
    },
    yTicks () {
      return this.yScale.ticks()
    },
    scaledEntities () {
    const xScale = this.xScale
    const yScale = this.yScale
    const data = this.data
    return data.map((essay, e) => {
        return essay.map((narration, n) => {
            return narration.entityTimePosition.map((entity) => {
                const targets = narration.targets
                return {
                        narration: e,
                        id: narration.resource,
                        textualLabel: entity.label,
                        cx: xScale(entity.x),
                        cy: this.compress ? this.sizes.height / 2 : yScale(entity.y),
                        radius: 2 + 1 * narration.targets.length,
                        type: narration.type,
                        context: narration.intervalContext,
                        innerText: entity.innerText,
                        uncertaintyScore: entity.indefinitness,
                        targets
                    }
                } )
            })
        }).flat(2)
    }
  },
  mounted () {
    this.calcContainerSize()
    window.addEventListener('resize', this.calcContainerSize, false)
 },
  methods: {
        calcContainerSize () {
          const { visualization } = this.$refs
          let cHeight = visualization.clientHeight
          let cWidth = visualization.clientWidth

          this.sizes.height = cHeight
          this.sizes.width = cWidth
    },
    storeRealScale (scale) {
      const logScaleTicks = scale.ticks(5)
      logScaleTicks.push(this.xValuesMode)
      this.xTicks = logScaleTicks
    }
  },
  updated () {
    this.calcContainerSize()
  },
  beforeDestroy () {
    window.removeEventListener('resize', this.calcContainerSize, false)
  }
}
</script>
